name: Deploy .NET API to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install EF tool
      run: dotnet tool install --global dotnet-ef

    - name: Add tools to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Restore dependencies
      run: dotnet restore

    # 🔥 IMPORTANT: RUN MIGRATIONS HERE (GITHUB SIDE)
    - name: Run EF migrations
      env:
        ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION }}
      run: dotnet ef database update --project Lactosure_api.csproj

    - name: Publish project
      run: dotnet publish Lactosure_api.csproj -c Release -o publish

    - name: Copy files to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 168.231.121.19
        username: root
        password: ${{ secrets.VPS_PASSWORD }}
        source: "publish/*"
        target: "/var/www/lactosure_api"

    - name: Restart API
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 168.231.121.19
        username: root
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          systemctl restart lactosure.service